greatkart/urls.py
from django.contrib import admin
from django.urls import path , include
from .views import *
from django.conf.urls.static import static
from django.conf import settings
app_name = 'greatkart'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home, name='home'),
    
    path('store/',include('store.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import *
app_name = 'store'
urlpatterns = [
    path('',store , name='store'),
    path('<slug:category_slug>/',store , name='products_by_category'),
    path('store/<slug:product_slug>/',product_details , name='products_details'),
]

store/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from autoslug import AutoSlugField  # Import AutoSlugField from django-autoslug
from category.models import *

class Product(models.Model):
    product_name = models.CharField(_('product name'), max_length=200)
    slug = AutoSlugField(_('slug'), unique=True, populate_from='product_name')  # Use AutoSlugField instead of SlugField
    description = models.TextField(_('description'), blank=True)
    price = models.DecimalField(_('price'), max_digits=10, decimal_places=2, help_text=_('in USD'))
    image = models.ImageField(_('image'), upload_to='products/')
    stock = models.PositiveIntegerField(_('stock'))
    is_available = models.BooleanField(_('is available'), default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name=_('category'))
    created_date = models.DateTimeField(_('created date'), auto_now_add=True)
    modified_date = models.DateTimeField(_('modified date'), auto_now=True)
    
    class Meta:
        verbose_name = _('product')
        verbose_name_plural = _('products')
        ordering = ['-created_date']

    def __str__(self):
        return self.product_name

    def is_in_stock(self):
        return self.stock > 0
    is_in_stock.boolean = True
    is_in_stock.short_description = _('in stock')



# import uuid
# from django.db import models
# from django.utils.translation import gettext_lazy as _
# from category.models import *
# from django.utils.text import slugify

# class Product(models.Model):
#     product_name = models.CharField(_('product name'), max_length=200)
#     slug = models.SlugField(_('slug'), unique=True, blank=True)
#     description = models.TextField(_('description'), blank=True)
#     price = models.DecimalField(_('price'), max_digits=10, decimal_places=2, help_text=_('in USD'))
#     image = models.ImageField(_('image'), upload_to='products/')
#     stock = models.PositiveIntegerField(_('stock'))
#     is_available = models.BooleanField(_('is available'), default=True)
#     category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name=_('category'))
#     created_date = models.DateTimeField(_('created date'), auto_now_add=True)
#     modified_date = models.DateTimeField(_('modified date'), auto_now=True)
    
#     class Meta:
#         verbose_name = _('product')
#         verbose_name_plural = _('products')
#         ordering = ['-created_date']

#     def __str__(self):
#         return self.product_name

#     def is_in_stock(self):
#         return self.stock > 0
#     is_in_stock.boolean = True
#     is_in_stock.short_description = _('in stock')

#     def save(self, *args, **kwargs):
#             if not self.slug:
#                 self.slug = slugify(self.product_name)
#                 # Check if the generated slug already exists
#                 while Product.objects.filter(slug=self.slug).exists():
#                     # If it does, append a number to make it unique
#                     self.slug = slugify(self.product_name) + '-' + str(uuid.uuid4())[:5]
#             super().save(*args, **kwargs)

store/views.py
from django.shortcuts import render , get_object_or_404
from .models import *
from category.models import *
# Create your views here.
def store(request,category_slug=None):
    categories = None
    products = None
    if  category_slug != None:
       
        categories = get_object_or_404(Category , slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        products_counts = products.count()
    else:    
        products = Product.objects.all()
        
        products_counts = products.count()
    
    context={
        'products' : products,
        'categories' : categories,
        'products_counts' : products_counts,
        
        
    }
    return render(request, 'store.html',context)

def product_details(request,product_slug):
    product = Product.objects.get(slug=product_slug)
    context = {
        'product' : product
    }
    return render(request , 'product-detail.html',context)
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="max-age=604800" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <title>GreatKart | One of the Biggest Online Shopping Platform</title>
    <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon" />

    <!-- jQuery -->
    <script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" />

    <!-- Font awesome 5 -->
    <link
      href="{% static 'fonts/fontawesome/css/all.min.css' %}"
      type="text/css"
      rel="stylesheet"
    />

    <!-- custom style -->
    <link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css" />
    <link
      href="{% static 'css/responsive.css' %}"
      rel="stylesheet"
      media="only screen and (max-width: 1200px)"
    />

    <!-- custom javascript -->
    <script src="{% static 'js/script.js' %}" type="text/javascript"></script>

    <script type="text/javascript">
      /// some script

      // jquery ready start
      $(document).ready(function () {
        // jQuery code
      });
      // jquery end
    </script>
  </head>
  <body>

    {% include "inc/navbar.html" %}

    {% block content %}
      
    {% endblock content %}

{% include "inc/footer.html" %}
        </body>
      </html>
      

templates/cart.html
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>GreatKart | One of the Biggest Online Shopping Platform</title>

<link href="images/favicon.ico" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="js/jquery-2.0.0.min.js" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="js/bootstrap.bundle.min.js" type="text/javascript"></script>
<link href="css/bootstrap.css" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="css/ui.css" rel="stylesheet" type="text/css"/>
<link href="css/responsive.css" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src="js/script.js" type="text/javascript"></script>

<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

}); 
// jquery end
</script>

</head>
<body>


<header class="section-header">
<nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
<div class="container">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTop4">
    <ul class="navbar-nav mr-auto">
    	<li class="nav-item dropdown">
		 	<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">   Language </a>
		    <ul class="dropdown-menu small">
				<li><a class="dropdown-item" href="#">English</a></li>
				<li><a class="dropdown-item" href="#">Arabic</a></li>
				<li><a class="dropdown-item" href="#">Russian </a></li>
		    </ul>
		</li>
		<li class="nav-item dropdown">
			<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> USD </a>
			<ul class="dropdown-menu small">
				<li><a class="dropdown-item" href="#">EUR</a></li>
				<li><a class="dropdown-item" href="#">AED</a></li>
				<li><a class="dropdown-item" href="#">RUBL </a></li>
		    </ul>
		</li>
    </ul>
    <ul class="navbar-nav">
		<li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
		<li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
	</ul> <!-- list-inline //  -->
  </div> <!-- navbar-collapse .// -->
</div> <!-- container //  -->
</nav>

<section class="header-main border-bottom">
	<div class="container">
<div class="row align-items-center">
	<div class="col-lg-2 col-md-3 col-6">
		<a href="./" class="brand-wrap">
			<img class="logo" src="./images/logo.png">
		</a> <!-- brand-wrap.// -->
	</div>
	<div class="col-lg col-sm col-md col-6 flex-grow-0">
		<div class="category-wrap dropdown d-inline-block float-right">
			<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> 
				<i class="fa fa-bars"></i> All category 
			</button>
			<div class="dropdown-menu">
				<a class="dropdown-item" href="#">Machinery / Mechanical Parts / Tools </a>
				<a class="dropdown-item" href="#">Consumer Electronics / Home Appliances </a>
				<a class="dropdown-item" href="#">Auto / Transportation</a>
				<a class="dropdown-item" href="#">Apparel / Textiles / Timepieces </a>
				<a class="dropdown-item" href="#">Home & Garden / Construction / Lights </a>
				<a class="dropdown-item" href="#">Beauty & Personal Care / Health </a> 
			</div>
		</div>  <!-- category-wrap.// -->
	</div> <!-- col.// -->
	<a href="./store.html" class="btn btn-outline-primary">Store</a>
	<div class="col-lg  col-md-6 col-sm-12 col">
		<form action="#" class="search">
			<div class="input-group w-100">
			    <input type="text" class="form-control" style="width:60%;" placeholder="Search">
			    
			    <div class="input-group-append">
			      <button class="btn btn-primary" type="submit">
			        <i class="fa fa-search"></i>
			      </button>
			    </div>
		    </div>
		</form> <!-- search-wrap .end// -->
	</div> <!-- col.// -->
	<div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
				<div class="d-flex justify-content-end mb-3 mb-lg-0">
					<div class="widget-header">
						<small class="title text-muted">Welcome guest!</small>
						<div> 
							<a href="./signin.html">Sign in</a> <span class="dark-transp"> | </span>
							<a href="./register.html"> Register</a>
						</div>
					</div>
					<a href="./cart.html" class="widget-header pl-3 ml-3">
						<div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
						<span class="badge badge-pill badge-danger notify">0</span>
					</a>
				</div> <!-- widgets-wrap.// -->
			</div> <!-- col.// -->
</div> <!-- row.// -->
	</div> <!-- container.// -->
</section> <!-- header-main .// -->



</header> <!-- section-header.// -->


<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->

<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="./images/items/11.jpg" class="img-sm"></div>
			<figcaption class="info">
				<a href="#" class="title text-dark">Camera Canon EOS M50 Kit</a>
				<p class="text-muted small">Matrix: 25 Mpx <br> Brand: Canon</p>
			</figcaption>
		</figure>
	</td>
	<td> 
		<!-- col.// -->
					<div class="col"> 
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
							<button class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </button>
							</div>
							<input type="text" class="form-control"  value="1">
							<div class="input-group-append">
							<button class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-plus"></i> </button>
							</div>
						</div> <!-- input-group.// -->
					</div> <!-- col.// -->
	</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price">$1156.00</var> 
			<small class="text-muted"> $315.20 each </small> 
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
	<a href="" class="btn btn-danger"> Remove</a>
	</td>
</tr>
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="./images/items/10.jpg" class="img-sm" alt=""></div>
			<figcaption class="info">
				<a href="#" class="title text-dark">ADATA Premier ONE microSDXC</a>
				<p class="text-muted small">Size: 256 GB  <br> Brand: ADATA </p>
			</figcaption>
		</figure>
	</td>
	<td> 
		<!-- col.// -->
					<div class="col"> 
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
							<button class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </button>
							</div>
							<input type="text" class="form-control"  value="1">
							<div class="input-group-append">
							<button class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-plus"></i> </button>
							</div>
						</div> <!-- input-group.// -->
					</div> <!-- col.// -->
	</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price">$149.97</var> 
			<small  class="text-muted"> $75.00 each </small>  
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
	<a href="" class="btn btn-danger"> Remove</a>
	</td>
</tr>
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="./images/items/9.jpg" class="img-sm" alt="" ></div>
			<figcaption class="info">
				<a href="#" class="title text-dark">Logitec headset for gaming</a>
				<p class="small text-muted">Version: CUH-ZCT2E  <br> Brand: Sony</p>
			</figcaption>
		</figure>
	</td>
	<td> 
		<!-- col.// -->
					<div class="col"> 
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
							<button class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </button>
							</div>
							<input type="text" class="form-control"  value="1">
							<div class="input-group-append">
							<button class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-plus"></i> </button>
							</div>
						</div> <!-- input-group.// -->
					</div> <!-- col.// -->
	</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price">$98.00</var> 
			<small class="text-muted"> $578.00 each</small> 
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
		<a href="" class="btn btn-danger"> Remove</a>
	</td>
</tr>
</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">$69.97</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> $10.00</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>$59.97</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="./images/misc/payments.png" height="26">
			</p>
			<a href="./place-order.html" class="btn btn-primary btn-block"> Checkout </a>
			<a href="./store.html" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  


    <!-- ========================= SECTION MAIN ========================= -->
 
    <!-- ========================= SECTION MAIN END// ========================= -->

    <!-- ========================= SECTION  ========================= -->
    <section class="section-name padding-y-sm">
      <div class="container">
        <header class="section-heading">
          <a href="./store.html" class="btn btn-outline-primary float-right"
            >See all</a
          >
          <h3 class="section-title">Popular products</h3>
        </header>
        <!-- sect-heading -->

        <div class="row">
          {% for product in products %}
          <div class="col-md-3">
            <div class="card card-product-grid">
              <a href="product-detail.html" class="img-wrap">
                <img src='{{product.image.url}}' />
              </a>
              <figcaption class="info-wrap">
                <a href="./product-detail.html" class="title"
                  >{{product.product_name}}</a
                >
                <div class="price mt-1">{{product.price}}</div>
                <!-- price-wrap.// -->
              </figcaption>
            </div>
          </div>
            
          {% endfor %}
          <!-- col.// -->
          {% comment %} <div class="col-md-3">
            <div class="card card-product-grid">
              <a href="./product-detail.html" class="img-wrap">
                <img src="images/items/2.jpg" />
              </a>
              <figcaption class="info-wrap">
                <a href="./product-detail.html" class="title"
                  >Some item name here</a
                >
                <div class="price mt-1">$280.00</div>
                <!-- price-wrap.// -->
              </figcaption>
            </div>
          </div>
          <!-- col.// -->
          <div class="col-md-3">
            <div class="card card-product-grid">
              <a href="./product-detail.html" class="img-wrap">
                <img src="images/items/3.jpg" />
              </a>
              <figcaption class="info-wrap">
                <a href="./product-detail.html" class="title"
                  >Great product name here</a
                >
                <div class="price mt-1">$56.00</div>
                <!-- price-wrap.// -->
              </figcaption>
            </div>
          </div>
          <!-- col.// -->
          <div class="col-md-3">
            <div class="card card-product-grid">
              <a href="./product-detail.html" class="img-wrap">
                <img src="images/items/4.jpg" />
              </a>
              <figcaption class="info-wrap">
                <a href="./product-detail.html" class="title"
                  >Just another product name</a
                >
                <div class="price mt-1">$179.00</div>
                <!-- price-wrap.// -->
              </figcaption>
            </div>
          </div>
          <!-- col.// -->
          <div class="col-md-3">
            <div class="card card-product-grid">
              <a href="./product-detail.html" class="img-wrap">
                <img src="images/items/5.jpg" />
              </a>
              <figcaption class="info-wrap">
                <a href="./product-detail.html" class="title"
                  >Just another product name</a
                >
                <div class="price mt-1">$179.00</div>
                <!-- price-wrap.// -->
              </figcaption>
            </div>
          </div>
          <!-- col.// -->
          <div class="col-md-3">
            <div class="card card-product-grid">
              <a href="./product-detail.html" class="img-wrap">
                <img src="images/items/6.jpg" />
              </a>
              <figcaption class="info-wrap">
                <a href="./product-detail.html" class="title"
                  >Some item name here</a
                >
                <div class="price mt-1">$280.00</div>
                <!-- price-wrap.// -->
              </figcaption>
            </div>
          </div>
          <!-- col.// -->
          <div class="col-md-3">
            <div class="card card-product-grid">
              <a href="./product-detail.html" class="img-wrap">
                <img src="images/items/7.jpg" />
              </a>
              <figcaption class="info-wrap">
                <a href="./product-detail.html" class="title"
                  >Great product name here</a
                >
                <div class="price mt-1">$56.00</div>
                <!-- price-wrap.// -->
              </figcaption>
            </div>
          </div>
          <!-- col.// -->
          <div class="col-md-3">
            <div class="card card-product-grid">
              <a href="./product-detail.html" class="img-wrap">
                <img src="images/items/9.jpg" />
              </a>
              <figcaption class="info-wrap">
                <a href="./product-detail.html" class="title"
                  >Just another product name</a
                >
                <div class="price mt-1">$179.00</div>
                <!-- price-wrap.// -->
              </figcaption>
            </div>
          </div> {% endcomment %}
          <!-- col.// -->
        </div>
        <!-- row.// -->
      </div>
      <!-- container // -->
    </section>
    <!-- ========================= SECTION  END// ========================= -->

	{% endblock content %}

templates/store.html
{% extends "base.html" %}


{% block content %}
  
    <!-- ========================= SECTION PAGETOP ========================= -->
    <section class="section-pagetop bg">
      <div class="container">
        <h2 class="title-page">Our Store</h2>
      </div>
      <!-- container //  -->
    </section>
    <!-- ========================= SECTION INTRO END// ========================= -->

    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">
      <div class="container">
        <div class="row">
          <aside class="col-md-3">
            <div class="card">
              <article class="filter-group">
                <header class="card-header">
                  <a
                    href="#"
                    data-toggle="collapse"
                    data-target="#collapse_1"
                    aria-expanded="true"
                    class=""
                  >
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Categories</h6>
                  </a>
                </header>
                <div
                  class="filter-content collapse show"
                  id="collapse_1"
                  style=""
                >
                  <div class="card-body">
                    <ul class="list-menu">
						<li><a href="{% url "store:store"  %}">all </a></li>
						{% for category in links %}
						<li><a href="{% url "store:products_by_category" category.slug  %}">{{category.category_name}} </a></li>
						{% endfor %}
                    </ul>
                  </div>
                  <!-- card-body.// -->
                </div>
              </article>
              <!-- filter-group  .// -->
              <article class="filter-group">
                <header class="card-header">
                  <a
                    href="#"
                    data-toggle="collapse"
                    data-target="#collapse_4"
                    aria-expanded="true"
                    class=""
                  >
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Sizes</h6>
                  </a>
                </header>
                <div
                  class="filter-content collapse show"
                  id="collapse_4"
                  style=""
                >
                  <div class="card-body">
                    <label class="checkbox-btn">
                      <input type="checkbox" />
                      <span class="btn btn-light"> XS </span>
                    </label>

                    <label class="checkbox-btn">
                      <input type="checkbox" />
                      <span class="btn btn-light"> SM </span>
                    </label>

                    <label class="checkbox-btn">
                      <input type="checkbox" />
                      <span class="btn btn-light"> LG </span>
                    </label>

                    <label class="checkbox-btn">
                      <input type="checkbox" />
                      <span class="btn btn-light"> XXL </span>
                    </label>
                  </div>
                  <!-- card-body.// -->
                </div>
              </article>
              <!-- filter-group .// -->

              <article class="filter-group">
                <header class="card-header">
                  <a
                    href="#"
                    data-toggle="collapse"
                    data-target="#collapse_3"
                    aria-expanded="true"
                    class=""
                  >
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Price range</h6>
                  </a>
                </header>
                <div
                  class="filter-content collapse show"
                  id="collapse_3"
                  style=""
                >
                  <div class="card-body">
                    <div class="form-row">
                      <div class="form-group col-md-6">
                        <label>Min</label>
                        <!-- <input class="form-control" placeholder="$0" type="number"> -->
                        <select class="mr-2 form-control">
                          <option value="0">$0</option>
                          <option value="50">$50</option>
                          <option value="100">$100</option>
                          <option value="150">$150</option>
                          <option value="200">$200</option>
                          <option value="500">$500</option>
                          <option value="1000">$1000</option>
                        </select>
                      </div>
                      <div class="form-group text-right col-md-6">
                        <label>Max</label>
                        <select class="mr-2 form-control">
                          <option value="50">$50</option>
                          <option value="100">$100</option>
                          <option value="150">$150</option>
                          <option value="200">$200</option>
                          <option value="500">$500</option>
                          <option value="1000">$1000</option>
                          <option value="2000">$2000+</option>
                        </select>
                      </div>
                    </div>
                    <!-- form-row.// -->
                    <button class="btn btn-block btn-primary">Apply</button>
                  </div>
                  <!-- card-body.// -->
                </div>
              </article>
              <!-- filter-group .// -->
            </div>
            <!-- card.// -->
          </aside>
          <!-- col.// -->
          <main class="col-md-9">
            <header class="border-bottom mb-4 pb-3">
              <div class="form-inline">
                <span class="mr-md-auto">{{products_counts}} Items found </span>
              </div>
            </header>
            <!-- sect-heading -->

            <div class="row">

				{% for product in products %}
				  
              <div class="col-md-4">
                <figure class="card card-product-grid">
                  <div class="img-wrap">
                    <img src="{{product.image.url}}" />
                  </div>
                  <!-- img-wrap.// -->
                  <figcaption class="info-wrap">
                    <div class="fix-height">
                      <a href="{% url "store:products_details" product.slug %}" class="title"
                        >{{product.product_name}}</a
                      >
                      <div class="price-wrap mt-2">
                        <span class="price">{{product.price}}</span>

                      </div>
                      <!-- price-wrap.// -->
                    </div>
					{% if product.stock <= 0 %}
					<h5 class="text-danger">out of stock</h5>
					{% else %}
					<a href="#" class="btn btn-block btn-primary"
					>Add to cart</a>

					{% endif %}
                  </figcaption>
                </figure>
              </div>
              <!-- col.// -->
			  {% endfor %}
{% comment %} 
              <div class="col-md-4">
                <figure class="card card-product-grid">
                  <div class="img-wrap">
                    <img src="images/items/2.jpg" />
                  </div>
                  <!-- img-wrap.// -->
                  <figcaption class="info-wrap">
                    <div class="fix-height">
                      <a href="./product-detail.html" class="title"
                        >Product name goes here just for demo item</a
                      >
                      <div class="price-wrap mt-2">
                        <span class="price">$1280</span>
						<del class="price-old">$1980</del>
                      </div>
                      <!-- price-wrap.// -->
                    </div>
                    <a href="#" class="btn btn-block btn-primary"
                      >Add to cart
                    </a>
					                    <a href="#" class="btn btn-block btn-success"
                      >Added to cart
                    </a>
                  </figcaption>
                </figure>
              </div> {% endcomment %}
  


              
            </div>
            <!-- row end.// -->

            <nav class="mt-4" aria-label="Page navigation sample">
              <ul class="pagination">
                <li class="page-item disabled">
                  <a class="page-link" href="#">Previous</a>
                </li>
                <li class="page-item active">
                  <a class="page-link" href="#">1</a>
                </li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                  <a class="page-link" href="#">Next</a>
                </li>
              </ul>
            </nav>
          </main>
          <!-- col.// -->
        </div>
      </div>
      <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
	{% endblock content %}